init  market-manager program
NascentCore/3k pull request #107
Opened 2023-09-25 09:38 UTC by RyanSxwl

init market-manager program

2023-09-25 10:13 UTC, yzhao-2023 requested changes
所有文件需要添加单元测试，否则会在 CI 测试中出现问题；具体做法：
1. 添加于代码文件对应的 _test.go 文件，如 foo.go foo_test.go 并编写测试
2. 在代码文件中顶层添加注释 // NO_TEST_NEEDED 来跳过上面的 CI 测试

CI 测试代码位于：
https://github.com/NascentCore/3k/blob/main/.github/scripts/check_go_tests.sh

另外你提交的代码太多，这会让代码审查者很难理解你的代码改动
（代码作者的目标应该是让代码审查者更容易理解代码改动）

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/doc/marker.sql
> +
删除空行

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/doc/marker.sql
需要注释届时这个文件的用处

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/cmd/main.go
> +	glog.V(0).Info("start marke manager ...")
marke 错别字

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/cmd/init/init.go
如果你要在 market-manager 里复制一份 [go project 标准目录结构](https://github.com/golang-standards/project-layout#cmd)，那你在顶层目录调整所有代码，而不是在 market-manager 里面

3k 目录下所有代码都属于同一个 go project

因此 go project 的标准结构应该从顶层开始

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/cmd/main.go
3k 目录下所有代码都属于同一个 go project

因此 go project 的标准结构应该从顶层开始

你如果需要，可以跟 @congpeiqing 说一下，把顶层目录的结构改成符合
https://github.com/golang-standards/project-layout
的结构，我完全同意你这么做
（只是一开始的时候想简单一些）

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/go.sum
删掉，直接使用顶层 go.sum

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/handler/db_client.go
> +func NewMmDb(dsn string) {
注释
特别是 dsn 的含义

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/logic/cpod.go
> +func CpodJobLogical(body []byte) (string, error) {
注释，特别是 body 的含义

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/logic/cpod.go
> +func CpodJobResultLogical(body []byte) (string, error) {
注释，特别是 body 的含义

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/logic/cpod.go
> +func CpodResourceLogical(body []byte) (string, error) {
注释，特别是 body 的含义

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/router/cpod.go
> +func CpodRouter(c *gin.Engine) {
注释

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/server/app_market.go
无意义的文件应该删除

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/server/cpod.go
> +func CpodJob(c *gin.Context) {
注释

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/server/cpod.go
> +func CpodJobResult(c *gin.Context) {
注释

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/internal/server/cpod.go
> +func CpodResource(c *gin.Context) {
注释

2023-09-25 10:13 UTC, yzhao-2023 commented on market-manager/pkg/db/cpod_resource.go
> +type CpodResources struct {
注释

2023-09-25 14:42 UTC, congpeiqing commented on market-manager/cmd/main.go
我觉得这个问题的思考和讨论可以延后进行

2023-09-26 03:15 UTC, RyanSxwl commented on market-manager/cmd/main.go
这个问题需要再讨论下

2023-09-26 11:00 UTC, yzhao-2023 commented on market-manager/cmd/main.go
有什么顾虑写在这里

2023-09-27 00:07 UTC, yzhao-2023 commented
https://github.com/NascentCore/3k/blob/main/common/errors/errors.go
类似的代码应该本仓库内的所有代码都可以重用

2023-09-27 07:19 UTC, congpeiqing reviewed
lgtm

2023-09-27 10:34 UTC, yzhao-2023 approved these changes

2023-09-27 10:34 UTC, merged