Resource data define
NascentCore/3k pull request #124
Opened 2023-10-09 11:40 UTC by congpeiqing

# Describe your changes
complete resource related data defination

## Issue
- [ ] Check this box if this PR fixes an issue, and then paste the link below
- [ ] No associated issue

## Test:
- [ ] Check this box if this PR has tests
- [ ] No test needed

2023-10-09 12:43 UTC, yzhao-2023 requested changes

2023-10-09 12:43 UTC, yzhao-2023 commented on manager/pkg/job/kubeflow-mpijob/mpijob_status.go
> +type KubeFlowMPIJobStatus struct {
改成
MPIJobStatus

2023-10-09 12:43 UTC, yzhao-2023 commented on manager/pkg/resource/resource.go
> +type GPU struct {
注释

2023-10-09 12:43 UTC, yzhao-2023 commented on manager/pkg/resource/resource.go
> +type GPUs struct {
注释

2023-10-09 12:43 UTC, yzhao-2023 commented on manager/pkg/resource/resource.go
>  }
为什么需要这个？

直接 CPodResourceDesc{} 即可？

2023-10-09 12:43 UTC, yzhao-2023 commented on manager/pkg/resource/resource_test.go
> +}
请检查输出结果
只检查结果不为空，那这个单元测试几乎没有价值

当然 ToJson 本身也没有存在的价值，如上面的评论所示

2023-10-10 01:34 UTC, congpeiqing commented on manager/pkg/resource/resource.go
>  }
目前是留空，上面有TODO

2023-10-10 01:40 UTC, congpeiqing commented on manager/pkg/job/kubeflow-mpijob/mpijob_status.go
> +type KubeFlowMPIJobStatus struct {
MPI Job的实现只有KubeFlow这一种吗？ 或者说只考虑这一种吗

2023-10-10 01:42 UTC, congpeiqing commented on manager/pkg/job/README.md
> +job is created by user , then scheduled by marketmanger , then cpodmanger get the job and run it.
前后都加了空格， 觉得这样看起来更清晰

2023-10-10 03:36 UTC, glen-nascentcoreai commented on manager/pkg/job/job.go
> +		return kubeflowmpijob.MPIJob{
目前，我们只有`JobTypeMPI`这一种类型的job？

2023-10-10 03:38 UTC, congpeiqing commented on manager/pkg/job/job.go
> +		return kubeflowmpijob.MPIJob{
是的，如果后面有其它的，这可以添加

2023-10-10 03:43 UTC, glen-nascentcoreai commented on manager/pkg/job/kubeflow-mpijob/mpijob.go
> +func (kfm MPIJob) genJsonData() map[string]interface{} {
`getJsonData`这个method只在这个package用？

另外，Go的缩进，我们统一改成2个space长的tab。这个以后我统一再说。

2023-10-10 03:48 UTC, glen-nascentcoreai commented on manager/pkg/resource/resource.go
> +type GPUs struct {
1、`GPUs`这个名字是个复数，但这是一个GPU的信息。在Linux里，有个virtual path：`/proc/cpuinfo`，我们是否参考这个，把这个类型的名字改为GPUInfo？
2、动态信息和静态信息分开，是否更好？

2023-10-10 04:30 UTC, yzhao-2023 approved these changes

2023-10-10 04:30 UTC, yzhao-2023 commented on manager/pkg/job/kubeflow-mpijob/mpijob.go
> +func (kfm MPIJob) genJsonData() map[string]interface{} {
https://github.com/NascentCore/3k/blob/eb93ad00dd42caf54bc109dedec36f0f53a78ed2/devops/linters/golangci.yaml#L93
golangci-lint 设置 2 space tab width
运行 tools/lint.sh 会自动格式化

2023-10-10 04:31 UTC, yzhao-2023 commented
请处理 @glen-nascentcoreai 提出的评论

2023-10-10 04:32 UTC, glen-nascentcoreai commented on manager/pkg/job/kubeflow-mpijob/mpijob.go
> +func (kfm MPIJob) genJsonData() map[string]interface{} {
除了indent，还有几个其他fmt方面的约定，根据Google officie Go style。我们需要定制一下fmt lint

2023-10-10 05:03 UTC, congpeiqing commented on manager/pkg/resource/resource.go
> +type GPUs struct {
1. GPUs是一个节点上的一组GPU的信息，我这里面另有一个单数的GPU struct, 代表一个GPU的信息。
2. 动态与静态信息分开我之前想过，没有想到很好的方案，主要考虑到在使用的时候很可能要做Join。 这个有没有可以参照的例子？

2023-10-10 05:07 UTC, congpeiqing commented on manager/pkg/job/kubeflow-mpijob/mpijob.go
> +func (kfm MPIJob) genJsonData() map[string]interface{} {
> `getJsonData`这个method只在这个package用？
> 
> 另外，Go的缩进，我们统一改成2个space长的tab。这个以后我统一再说。

genJsonData目录是只在包内使用的，目前是设计这个package对外提供了一组相对高层的API，细节没有暴露

2023-10-10 05:32 UTC, merged

2023-10-10 05:43 UTC, glen-nascentcoreai commented on manager/pkg/resource/resource.go
> +type GPUs struct {
这个地方需要再捋一下，至少有两个维度。

维度1：homogeneous vs heterogeneous。

- homogeneous GPUs in a single machine，实际生产环境中99%都是这样。
- heterogeneous GPUs in a single machine，这个情况先不用考虑。

维度二：静态信息 vs 动态信息。

据此，先定义一个type，表示一个GPU的静态信息：
```
type GPUInfo struct {
}
```
然后，同一个机器上的多个或所有GPU的静态信息，就是一个`GPUInfo` array或slice就行了。甚至，这个都是不必要的。

定义一个type，表示一个GPU的动态信息（比如，Utilization、memory usage、power usage、temperature等等，可以参考`nvidia-smi`命令的输出。
```
type GPUState struct {
}
```
然后，一个机器上所有GPU的states，可以用一个array或map表示。用map的话，key就是device Id/rank，整数，从0开始。这也是为什么，也可以用array表示。

2023-10-10 06:06 UTC, congpeiqing commented on manager/pkg/resource/resource.go
> +type GPUs struct {
静态信息这部分，对于同一个节点上的所有GPU，是不是有一个就够了？

2023-10-10 06:10 UTC, glen-nascentcoreai commented on manager/pkg/resource/resource.go
> +type GPUs struct {
对，因为是homogeneous。如果就是想表示所有GPUs on a single node，用array（slice）或map。map的话，key就是rank/device Id，整型，从0开始，连续递增。

2023-10-10 06:10 UTC, congpeiqing commented on manager/pkg/resource/resource.go
> +type GPUs struct {
另外，我了解Nvidia的GPU同一型号可能会有不同显存的版本，比如16G版24G版， 这种不同版本的GPU放在同一机器上是不是常见，或者说是不是我们要考虑支持的？

2023-10-10 06:19 UTC, glen-nascentcoreai commented on manager/pkg/resource/resource.go
> +type GPUs struct {
这种情况，model number等信息是不一样的。实际中，很少一起在一台机器上，我们目前先不用考虑。
其实，这种情况并不难扩展。